version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    image: php7.4
    container_name: app_laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - localhost
  db:
    build: ./.docker/mysql
    container_name: app_mysql
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_USER: mysql
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - localhost
    ports:
      - 33006:3306
  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d
    networks:
      - localhost
  redis:
    image: redis:alpine
    container_name: app_redis
    ports:
      - "6382:6379"
    networks:
      - localhost
networks:
  localhost:
    driver: bridge
